#services:
#  elasticsearch:
#    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
#    environment:
#      - 'ELASTIC_PASSWORD=secret'
#      - 'discovery.type=single-node'
#      - 'xpack.security.enabled=false'
#    ports:
#      - '9200'
#      - '9300'


version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - es-net
    volumes:
      - esdata:/usr/share/elasticsearch/data

#  springboot-app:
#    image: elastic-sample-app:latest
#    container_name: elastic-sample-app
#    depends_on:
#      - elasticsearch
#    environment:
#      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
#    ports:
#      - "8080:8080"
#    networks:
#      - es-net
#    build:
#      context: .
#      dockerfile: Dockerfile

volumes:
  esdata:
    driver: local

networks:
  es-net:
    driver: bridge
