services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
#      - ELASTIC_USERNAME=elastic
#      - ELASTIC_PASSWORD=elastic_pass
    ports:
      - "9200:9200"
    networks:
      - es-net
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local

networks:
  es-net:
    driver: bridge
